server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
#    测试数据库
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://111.231.120.239:3306/cjw_test?useUnicode=true&zeroDateTimeBehavior=convertToNull
      username: cjw_test
      password: cjw_test2018
      initialSize: 10
      maxActive: 20
      minIdle: 5
      maxWait: 50000

#    生产数据库
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://111.231.120.239:3306/cjw_db?useUnicode=true&zeroDateTimeBehavior=convertToNull
#      username: cjw_db
#      password: cjw_db2018
#      initialSize: 10
#      maxActive: 100
#      minIdle: 5
#      maxIdle: 20
#      maxWait: 50000

#上传文件
file:
  staticAccessPath: /api/file/**
  uploadPath: E:/computerStudy/Git/cjw_all/cjw/upload/

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cjw.dao.entity

# 打印sql
logging:
  level:
    com.cjw.dao.mapper: DEBUG

#微信
wx:
  api: https://api.weixin.qq.com/sns/jscode2session
  appId: wxe12df03a91262d60
  secret: 92c30f6fc262872bbfa88ad66f452b20

webSocket:
  url: "/webSocketServer"