server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cjw_db?useUnicode=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
#    initialSize: 10
#    maxActive: 100
#    minIdle: 5
#    maxIdle: 20
#    maxWait: 50000
#    测试数据库
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://111.231.120.239:3306/cjw_test?useUnicode=true&zeroDateTimeBehavior=convertToNull
      username: cjw_test
      password: cjw_test2018
      initialSize: 10
      maxActive: 100
      minIdle: 5
      maxIdle: 20
      maxWait: 50000

#    生产数据库
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://111.231.120.239:3306/cjw_db?useUnicode=true&zeroDateTimeBehavior=convertToNull
#      username: cjw_db
#      password: cjw_db2018
#      initialSize: 10
#      maxActive: 100
#      minIdle: 5
#      maxIdle: 20
#      maxWait: 50000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cjw.Dao.Entity

# 打印sql
logging:
  level:
    com.cjw.dao.mapper: DEBUG

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

wx:
  api: https://api.weixin.qq.com/sns/jscode2session
  appId: wxe12df03a91262d60
  secret: 92c30f6fc262872bbfa88ad66f452b20